services:
  web:
    build: .
    ports: ["8000"]
    depends_on: [inner]
    x-kedge:
      auth:
        google: true
        github: true
  inner:
    image: docker.io/traefik/whoami:latest
    expose:
      - 80
